version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
    parallelism: 1
  test:
    working_directory: ~/usr/app
    docker:
      - image: circleci/node:10.15.3
      # PostgreSQL service container image available at `host: localhost`
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-ci-test
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Linting
          command: yarn lint-staged
      - run:
          name: Unit & Integration Tests & Coverage
          command: yarn test:ci
      - codecov/upload:
          file: ~/usr/app/src/coverage/lcov.info
    parallelism: 3
workflows:
  version: 2.1
  build_lint_test:
    jobs:
      - build
      - test
